openapi: 3.0.3
info:
  title: Job Logging
  version: 1.0.0
  description: Job Logging End Points
servers:
  - url: http://localhost:8080

paths:
  /user/{userName}:
    get:
      summary: Fetch user details by username
      description: Returns a user's full details based on the userName
      operationId: getUser
      tags:
        - user
      parameters:
        - name: userName
          in: path
          required: true
          description: The username used to fetch user details
          schema:
            type: string
      responses:
        200:
          description: User details fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailsDTO'
        404:
          description: User not found

components:
  schemas:
    UserDetailsDTO:
      type: object
      properties:
        userName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        confirmPassword:
          type: string
        dateOfBirth:
          type: date
